apiVersion: v1
kind: PersistentVolume
metadata:
  name: base-persistencia
  labels:
    type: primero
spec:
  storageClassName: sistema
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"